services:
    _defaults:
        autowire: true
        autoconfigure: true

    Doctrine\ORM\EntityManagerInterface:
        alias: doctrine.orm.entity_manager

    App\Service\MovieDbApiService:
        arguments:
            $apiKey: '%env(MOVIE_DB_API_KEY)%'

    App\Controller\ApiController:
        arguments:
            $movieDbApiService: '@App\Service\MovieDbApiService'
        tags: ['controller.service_arguments']

    App\Controller\MovieController:
        arguments:
            $movieDbApiService: '@App\Service\MovieDbApiService'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
