
parameters:

services:
  
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    # Alias for the EntityManagerInterface
    Doctrine\ORM\EntityManagerInterface:
        alias: doctrine.orm.entity_manager
    
    
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    
    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    